version: '3'
services:

  worker0:
    build: ./db
    container_name: w0
    restart: always
    ports:
      - "8080:8080"
  
  worker1:
    build: ./db
    container_name: w1
    restart: always
    ports:
      - "8081:8080"
  
  worker2:
    build: ./db
    container_name: w2
    restart: always
    ports:
      - "8082:8080"

  worker3:
    build: ./db
    container_name: w3
    restart: always
    ports:
      - "8083:8080"

  bootstrap:
    build: ./bootstrapping
    container_name: boot
    restart: always
    ports:
      - "7070:7070"
    depends_on:
      - worker0
      - worker1
      - worker2
      - worker3
  
  web:
    build: ./web
    container_name: web
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - bootstrap

